version: "3"
services:
  postgres:
    image: postgres:15-alpine # set porgres instead of postgis/postgis:15-3.3-alpine if you don't need postgis
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:  
      - ./pgdata:/var/lib/postgresql/data:delegated
    ports:
      - 7654:5432
