# Use the Bitnami Airflow image
FROM bitnami/airflow:latest

COPY entrypoint.sh /entrypoint.sh

COPY requirements.txt /requirements.txt

RUN pip3 install --no-cache-dir -r /requirements.txt
USER root
RUN chmod +x /entrypoint.sh
USER 1001

# Set ARG for build-time variables
ARG AIRFLOW_DATABASE_PASSWORD
ARG AIRFLOW_DATABASE_USERNAME
ARG AIRFLOW_EMAIL
ARG AIRFLOW_EXECUTOR
ARG AIRFLOW__CELERY__BROKER_URL
ARG AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
ARG AIRFLOW_USERNAME
ARG AIRFLOW_PASSWORD
ARG AIRFLOW__CORE__DAGS_FOLDER
ARG AIRFLOW__CORE__ENABLE_XCOM_PICKLING
ARG AIRFLOW__CORE__LOAD_EXAMPLES
ARG AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER
ARG AIRFLOW__CORE__REMOTE_LOG_CONN_ID
ARG AIRFLOW__CORE__REMOTE_LOGGING
ARG AIRFLOW__WEBSERVER__EXPOSE_CONFIG

ENV AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_DATABASE_PASSWORD} \
    AIRFLOW_DATABASE_USERNAME=${AIRFLOW_DATABASE_USERNAME} \
    AIRFLOW_EMAIL=${AIRFLOW_EMAIL} \
    AIRFLOW_EXECUTOR=${AIRFLOW_EXECUTOR} \
    AIRFLOW__CELERY__BROKER_URL=${AIRFLOW__CELERY__BROKER_URL} \
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN} \
    AIRFLOW_DATABASE_NAME=bitnami_airflow \
    AIRFLOW_USERNAME=${AIRFLOW_USERNAME} \
    AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD} \
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080 \
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING=${AIRFLOW__CORE__ENABLE_XCOM_PICKLING} \
    AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES} \
    AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=${AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER} \
    AIRFLOW__CORE__REMOTE_LOG_CONN_ID=${AIRFLOW__CORE__REMOTE_LOG_CONN_ID} \
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG=${AIRFLOW__WEBSERVER__EXPOSE_CONFIG}

EXPOSE 8080

RUN airflow db migrate
# create an admin user
RUN airflow users create \
    --username $AIRFLOW_USERNAME \
    --firstname hamza \
    --lastname hamza \
    --role Admin \
    --email $AIRFLOW_EMAIL \
    --password $AIRFLOW_PASSWORD

# Launch the start script
CMD ["/entrypoint.sh"]
